alter table portal_permissions
  add column if not exists can_view boolean not null default true;

-- Existing rows represent an administrator's prior lock/unlock decisions.
-- The new column defaults those rows to visible so previously configured
-- modules immediately appear in role navigation. Only newly introduced rows
-- use the conservative visibility and mutation defaults below.

insert into portal_permissions (role, module, can_view, can_edit, can_delete)
values
  ('assistant', 'affiliations', true, false, false),
  ('assistant', 'campus_report', true, false, false),
  ('assistant', 'syllabus_report', true, false, false),
  ('assistant', 'overall_classes_summary', false, false, false),
  ('assistant', 'users', false, false, false),
  ('assistant', 'students', true, false, false),
  ('assistant', 'teachers', true, false, false),
  ('assistant', 'departments', true, false, false),
  ('assistant', 'classes', true, false, false),
  ('assistant', 'courses', true, false, false),
  ('assistant', 'semesters', true, false, false),
  ('assistant', 'allocations', true, false, false),
  ('assistant', 'timetables', true, false, false),
  ('assistant', 'attendance', true, false, false),
  ('assistant', 'student_attendance', true, false, false),
  ('assistant', 'daily_attendance', true, false, false),
  ('assistant', 'billing', true, false, false),
  ('assistant', 'fines', false, false, false),
  ('assistant', 'results', true, false, false),
  ('assistant', 'dept_attendance', true, false, false),
  ('assistant', 'course_attendance', true, false, false),
  ('assistant', 'leave_management', true, false, false),
  ('assistant', 'dit_mock', true, false, false),
  ('assistant', 'rollno_slips', false, false, false),
  ('assistant', 'notifications', true, false, false),
  ('coordinator', 'affiliations', false, false, false),
  ('coordinator', 'campus_report', false, false, false),
  ('coordinator', 'syllabus_report', false, false, false),
  ('coordinator', 'overall_classes_summary', false, false, false),
  ('coordinator', 'users', false, false, false),
  ('coordinator', 'students', true, false, false),
  ('coordinator', 'teachers', false, false, false),
  ('coordinator', 'departments', false, false, false),
  ('coordinator', 'classes', false, false, false),
  ('coordinator', 'courses', false, false, false),
  ('coordinator', 'semesters', true, false, false),
  ('coordinator', 'allocations', false, false, false),
  ('coordinator', 'timetables', false, false, false),
  ('coordinator', 'attendance', true, false, false),
  ('coordinator', 'student_attendance', true, false, false),
  ('coordinator', 'daily_attendance', false, false, false),
  ('coordinator', 'billing', true, false, false),
  ('coordinator', 'fines', true, false, false),
  ('coordinator', 'results', false, false, false),
  ('coordinator', 'dept_attendance', false, false, false),
  ('coordinator', 'course_attendance', false, false, false),
  ('coordinator', 'leave_management', false, false, false),
  ('coordinator', 'dit_mock', false, false, false),
  ('coordinator', 'rollno_slips', false, false, false),
  ('coordinator', 'notifications', false, false, false),
  ('hod', 'affiliations', false, false, false),
  ('hod', 'campus_report', false, false, false),
  ('hod', 'syllabus_report', false, false, false),
  ('hod', 'overall_classes_summary', false, false, false),
  ('hod', 'users', false, false, false),
  ('hod', 'students', true, false, false),
  ('hod', 'teachers', false, false, false),
  ('hod', 'departments', false, false, false),
  ('hod', 'classes', true, false, false),
  ('hod', 'courses', false, false, false),
  ('hod', 'semesters', false, false, false),
  ('hod', 'allocations', false, false, false),
  ('hod', 'timetables', false, false, false),
  ('hod', 'attendance', false, false, false),
  ('hod', 'student_attendance', true, false, false),
  ('hod', 'daily_attendance', false, false, false),
  ('hod', 'billing', false, false, false),
  ('hod', 'fines', false, false, false),
  ('hod', 'results', true, false, false),
  ('hod', 'dept_attendance', true, false, false),
  ('hod', 'course_attendance', false, false, false),
  ('hod', 'leave_management', false, false, false),
  ('hod', 'dit_mock', false, false, false),
  ('hod', 'rollno_slips', true, false, false),
  ('hod', 'notifications', true, false, false),
  ('finance_manager', 'affiliations', false, false, false),
  ('finance_manager', 'campus_report', false, false, false),
  ('finance_manager', 'syllabus_report', false, false, false),
  ('finance_manager', 'overall_classes_summary', false, false, false),
  ('finance_manager', 'users', false, false, false),
  ('finance_manager', 'students', false, false, false),
  ('finance_manager', 'teachers', true, false, false),
  ('finance_manager', 'departments', true, false, false),
  ('finance_manager', 'classes', true, false, false),
  ('finance_manager', 'courses', false, false, false),
  ('finance_manager', 'semesters', false, false, false),
  ('finance_manager', 'allocations', true, false, false),
  ('finance_manager', 'timetables', true, false, false),
  ('finance_manager', 'attendance', true, false, false),
  ('finance_manager', 'student_attendance', false, false, false),
  ('finance_manager', 'daily_attendance', false, false, false),
  ('finance_manager', 'billing', true, false, false),
  ('finance_manager', 'fines', true, false, false),
  ('finance_manager', 'results', false, false, false),
  ('finance_manager', 'dept_attendance', false, false, false),
  ('finance_manager', 'course_attendance', false, false, false),
  ('finance_manager', 'leave_management', false, false, false),
  ('finance_manager', 'dit_mock', false, false, false),
  ('finance_manager', 'rollno_slips', false, false, false),
  ('finance_manager', 'notifications', false, false, false)
on conflict (role, module) do nothing;

create index if not exists idx_portal_permissions_module
  on portal_permissions(module);