"use client";
import { useEffect, useState } from "react";
import toast from "react-hot-toast";
import { DataFetchLoader, ButtonLoader } from "@/components/ui/Loaders";
type Row={id:string;category:string;status:string;created_at:string;student_name:string;contact:string|null;class_name:string;session:string;active_semester:string|null};
type Detail={complaint:Row&{body:string;other_issue?:string};attachments:{id:string;url:string}[];comments:{id:string;author_role:string;body:string;created_at:string}[];status_history:{id:string;status:string;created_at:string}[]};
const statuses=["submitted","open","in_progress","resolved","rejected"];
const nice=(s:string)=>s.replace(/_/g," ");
export default function AdminFeedbackManager(){
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[filter,setFilter]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[reply,setReply]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await fetch("/api/admin/feedback");if(r.ok)setRows(await r.json());else toast.error("Unable to load feedback.");}finally{setLoading(false);}};useEffect(()=>{load();},[]);
 async function open(id:string){const r=await fetch(`/api/admin/feedback/${id}`);if(r.ok)setDetail(await r.json());else toast.error("Unable to open feedback.");}
 async function send(){if(!detail||!reply.trim())return;setBusy(true);try{const r=await fetch(`/api/admin/feedback/${detail.complaint.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:reply})});if(!r.ok)throw Error();setReply("");toast.success("Reply sent.");open(detail.complaint.id);}catch{toast.error("Unable to send reply.");}finally{setBusy(false);}}
 async function status(status:string){if(!detail)return;setBusy(true);try{const r=await fetch(`/api/admin/feedback/${detail.complaint.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});if(!r.ok)throw Error();toast.success("Status updated.");open(detail.complaint.id);load();}catch{toast.error("Unable to update status.");}finally{setBusy(false);}}
 const visible=filter?rows.filter(r=>r.status===filter):rows;
 return <div className="space-y-5"><div><h1 className="text-xl font-bold text-slate-900 dark:text-white">Feedback System</h1><p className="text-sm text-slate-500">Review and respond to student complaints.</p></div><div className="card-3d overflow-x-auto p-4"><div className="mb-4 flex justify-end"><select value={filter} onChange={e=>setFilter(e.target.value)} className="input"><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>{loading?<DataFetchLoader label="Loading complaints…" />:<table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-500"><th className="p-3">Student Name</th><th className="p-3">Class + Session</th><th className="p-3">Semester</th><th className="p-3">Cell No.</th><th className="p-3">Complaint About</th><th className="p-3">Status</th><th className="p-3">View</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} className="border-b last:border-0 dark:border-slate-700"><td className="p-3">{r.student_name}</td><td className="p-3">{r.class_name} · {r.session}</td><td className="p-3">{r.active_semester||"—"}</td><td className="p-3">{r.contact||"—"}</td><td className="p-3">{r.category}</td><td className="p-3 capitalize">{nice(r.status)}</td><td className="p-3"><button onClick={()=>open(r.id)} className="text-indigo-600 hover:underline">View</button></td></tr>)}</tbody></table>}</div>
 {detail&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>setDetail(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white p-5 dark:bg-slate-900" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2 className="text-lg font-semibold">Complaint details</h2><button onClick={()=>setDetail(null)}>✕</button></div><div className="mt-4 text-sm"><p><b>{detail.complaint.student_name}</b> · {detail.complaint.category}</p><p className="mt-3 whitespace-pre-wrap">{detail.complaint.body}</p>{detail.complaint.other_issue&&<p className="mt-2 text-slate-500">Issue: {detail.complaint.other_issue}</p>}</div><div className="mt-3 flex gap-2">{detail.attachments.map(a=><a key={a.id} href={a.url} target="_blank" rel="noreferrer"><img alt="Feedback attachment" src={a.url} className="h-20 w-20 rounded object-cover"/></a>)}</div><div className="mt-4 flex items-center gap-3"><span className="text-sm font-medium">Status</span><select disabled={busy} value={detail.complaint.status} onChange={e=>status(e.target.value)} className="input capitalize">{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-4 space-y-2">{detail.status_history.map(h=><p key={h.id} className="text-xs text-slate-500">{new Date(h.created_at).toLocaleString()} — {nice(h.status)}</p>)}{detail.comments.map(c=><div key={c.id} className={`rounded-lg p-3 text-sm ${c.author_role==="admin"?"bg-indigo-50 dark:bg-indigo-500/10":"bg-slate-100 dark:bg-slate-800"}`}><b>{c.author_role==="admin"?"Admin":"Student"}</b><p>{c.body}</p><small>{new Date(c.created_at).toLocaleString()}</small></div>)}</div><div className="mt-4 flex gap-2"><textarea value={reply} onChange={e=>setReply(e.target.value)} className="input min-h-20 flex-1" placeholder="Reply to student…"/><button disabled={busy||!reply.trim()} onClick={send} className="grad-primary self-end rounded px-3 py-2 text-sm text-white">{busy?<ButtonLoader/>:"Reply"}</button></div></div></div>}</div>;
}