"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { FileDown, Printer, Search, X } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import toast from "react-hot-toast";
import { escapePrintHtml, printHtmlDocument } from "@/lib/printDocument";

type Zone = "toppers" | "good" | "average" | "warning" | "danger";
const zones: Zone[] = ["toppers", "good", "average", "warning", "danger"];
const zoneLabels: Record<Zone, string> = { toppers: "Toppers", good: "Good", average: "Average", warning: "Warning", danger: "Danger" };
const zoneName = (value: unknown) => { const key = String(value); return Object.prototype.hasOwnProperty.call(zoneLabels, key) ? zoneLabels[key as Zone] : key; };
const zoneColors: Record<Zone, string> = { toppers: "#10b981", good: "#3b82f6", average: "#f59e0b", warning: "#f97316", danger: "#ef4444" };
type AnyRecord = Record<string, any>;
const localDate = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
const monthStart = () => { const d = new Date(); return localDate(new Date(d.getFullYear(), d.getMonth(), 1)); };
const monthEnd = () => { const d = new Date(); return localDate(new Date(d.getFullYear(), d.getMonth() + 1, 0)); };
const weekStart = () => { const d = new Date(); const day = d.getDay(); d.setDate(d.getDate() - (day === 0 ? 6 : day - 1)); return localDate(d); };
const weekEnd = () => { const d = new Date(); const day = d.getDay(); d.setDate(d.getDate() + (day === 0 ? 0 : 7 - day)); return localDate(d); };
const options = (v: any): { value: string; label: string }[] => (Array.isArray(v) ? v : []).map((x: any) => typeof x === "string" ? { value: x, label: x } : { value: String(x.id ?? x.value ?? x.course_id ?? ""), label: String(x.name ?? x.label ?? x.title ?? x.course_title ?? x.id ?? "") + (x.session ? ` (${x.session})` : "") }).filter((x: { value: string }) => x.value);
const testKey = (t: AnyRecord) => `${t.date ?? t.test_date}|${t.test_number ?? t.test_series_id ?? t.series_name}|${t.course_code ?? t.course_id}`;

function printTable(title: string, columns: string[], rows: string[][], header = "") {
  const h = columns.map((x) => `<th>${escapePrintHtml(x)}</th>`).join("");
  const b = rows.map((r) => `<tr>${r.map((x) => `<td>${escapePrintHtml(String(x ?? "—"))}</td>`).join("")}</tr>`).join("");
  void printHtmlDocument(`<html><head><title>${escapePrintHtml(title)}</title><style>body{font:12px Arial;color:#172033;padding:24px}h1{color:#3730a3}table{border-collapse:collapse;width:100%;margin-top:18px}th{background:#3730a3;color:#fff}th,td{border:1px solid #cbd5e1;padding:6px;text-align:left}@media print{body{padding:0}}</style></head><body>${header}<h1>${escapePrintHtml(title)}</h1><table><thead><tr>${h}</tr></thead><tbody>${b}</tbody></table></body></html>`, title);
}

export default function DitAnalytics() {
  const [tab, setTab] = useState<"subjects" | "result" | "zones">("subjects");
  const [from, setFrom] = useState(monthStart), [to, setTo] = useState(monthEnd);
  const [zoneFrom, setZoneFrom] = useState(weekStart), [zoneTo, setZoneTo] = useState(weekEnd);
  const [filters, setFilters] = useState<AnyRecord>({}), [zoneFilters, setZoneFilters] = useState<AnyRecord>({});
  const [subjects, setSubjects] = useState<AnyRecord[]>([]), [summary, setSummary] = useState<AnyRecord>({});
  const [optionsData, setOptionsData] = useState<AnyRecord>({}), [zoneOptionsData, setZoneOptionsData] = useState<AnyRecord>({});
  const [loading, setLoading] = useState(false), [zoneLoading, setZoneLoading] = useState(false);
  const [studentQ, setStudentQ] = useState(""), [students, setStudents] = useState<AnyRecord[]>([]);
  const [studentId, setStudentId] = useState(""), [report, setReport] = useState<AnyRecord | null>(null);
  const [selectedZone, setSelectedZone] = useState<Zone>("toppers"), [zoneData, setZoneData] = useState<AnyRecord | null>(null);
  const [detail, setDetail] = useState<AnyRecord | null>(null);
  const subjectQuery = (extra: AnyRecord = {}) => new URLSearchParams({ from_date: from, to_date: to, ...Object.fromEntries(Object.entries(filters).filter(([k, v]) => k !== "__options" && v)), ...extra }).toString();
  const zoneQuery = (extra: AnyRecord = {}) => new URLSearchParams({ from_date: zoneFrom, to_date: zoneTo, scope: "overall", ...Object.fromEntries(Object.entries(zoneFilters).filter(([, v]) => v)), ...extra }).toString();
  const loadSubjects = async () => { setLoading(true); try { const r = await fetch(`/api/admin/dit/analytics?${subjectQuery()}`); const d = await r.json(); if (!r.ok) throw new Error(d.error); setSubjects(d.subjects ?? []); setSummary(d.summary ?? {}); setOptionsData(d.filter_options ?? {}); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to load analytics."); } finally { setLoading(false); } };
  useEffect(() => { void loadSubjects(); }, [from, to]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (studentQ.trim().length < 2) { setStudents([]); return; } const timer = setTimeout(async () => { try { const d = await (await fetch(`/api/admin/dit/analytics/student-search?q=${encodeURIComponent(studentQ)}`)).json(); setStudents(Array.isArray(d) ? d : d.students ?? []); } catch { /* optional search */ } }, 350); return () => clearTimeout(timer); }, [studentQ]);
  async function loadReport() { if (!studentId) return toast.error("Select a student first."); try { const d = await (await fetch(`/api/admin/dit/analytics/student-report?${subjectQuery({ student_id: studentId })}`)).json(); if (d.error) throw new Error(d.error); setReport(d); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to load report."); } }
  async function loadZones(zone = selectedZone) { setSelectedZone(zone); setZoneLoading(true); try { const d = await (await fetch(`/api/admin/dit/analytics/zones?${zoneQuery({ zone })}`)).json(); if (d.error) throw new Error(d.error); setZoneData(d); setZoneOptionsData(d.filter_options ?? {}); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to load zones."); } finally { setZoneLoading(false); } }
  async function loadSubjectZone(zone: Zone, courseId: string) { try { const d = await (await fetch(`/api/admin/dit/analytics/zones?${subjectQuery({ scope: "subject", zone, course_id: courseId })}`)).json(); if (d.error) throw new Error(d.error); setDetail(d); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to load zone details."); } }
  const filterFields = [["test_series_id", "Test series"], ["class_id", "Class"], ["semester_id", "Semester"], ["course_id", "Course"]];
  useEffect(() => { if (tab === "zones" && !zoneData) void loadZones(); }, [tab]); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="space-y-5">
    <div className="flex flex-wrap gap-2 border-b">{([["subjects", "Subject Analytics"], ["result", "Overall Result"], ["zones", "Overall Zones"]] as const).map(([v, l]) => <button key={v} onClick={() => setTab(v)} className={`border-b-2 px-3 py-2 text-sm font-semibold ${tab === v ? "border-indigo-600 text-indigo-600" : "border-transparent text-slate-500"}`}>{l}</button>)}</div>
    {tab === "subjects" && <><DateFilters from={from} to={to} setFrom={setFrom} setTo={setTo} /><div className="flex flex-wrap gap-2 rounded-xl border bg-white p-4">{filterFields.map(([k, l]) => <Select key={k} label={l} value={filters[k] ?? ""} values={options(optionsData[k] ?? optionsData[k.replace("_id", "s")])} onChange={(v: string) => setFilters({ ...filters, [k]: v })} />)}<button onClick={() => void loadSubjects()} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">{loading ? "Loading…" : "Apply filters"}</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Subjects", subjects.length], ["Tests", subjects.reduce((n, s) => n + Number(s.test_count ?? 0), 0)], ["Students", summary.unique_student_count ?? 0], ["Passing", `${subjects.length ? (subjects.reduce((n, s) => n + Number(s.passing_percentage ?? 0), 0) / subjects.length).toFixed(1) : "0.0"}%`]].map(([l, v]) => <div key={String(l)} className="rounded-xl border bg-white p-4"><div className="text-xs text-slate-500">{l}</div><div className="text-2xl font-bold">{v}</div></div>)}</div><SubjectChart subjects={subjects} /><SubjectCards subjects={subjects} onZone={loadSubjectZone} /></>}
    {tab === "result" && <ResultScreen from={from} to={to} setFrom={setFrom} setTo={setTo} studentQ={studentQ} setStudentQ={setStudentQ} students={students} setStudentId={setStudentId} setStudents={setStudents} loadReport={loadReport} report={report} />}
    {tab === "zones" && <ZonesScreen from={zoneFrom} to={zoneTo} setFrom={setZoneFrom} setTo={setZoneTo} filters={zoneFilters} setFilters={setZoneFilters} optionsData={zoneOptionsData} selected={selectedZone} load={loadZones} data={zoneData} loading={zoneLoading} detail={detail} setDetail={setDetail} />}
    {detail && tab === "subjects" && <SubjectDetail detail={detail} close={() => setDetail(null)} />}
  </div>;
}

function DateFilters({ from, to, setFrom, setTo }: any) { return <div className="flex flex-wrap gap-3 rounded-xl border bg-white p-4"><label className="text-xs font-semibold">From<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="mt-1 block rounded border px-2 py-1.5" /></label><label className="text-xs font-semibold">To<input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="mt-1 block rounded border px-2 py-1.5" /></label></div>; }
function Select({ label, value, values, onChange }: any) { return <label className="text-xs font-semibold text-slate-500">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 block max-w-[190px] rounded border px-2 py-2 text-sm"><option value="">All</option>{values.map((o: any) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>; }
function SubjectChart({ subjects }: { subjects: AnyRecord[] }) { const data = subjects.map((s) => ({ name: s.course_code || s.course_title, passing: Number(s.passing_percentage ?? 0), ...Object.fromEntries(zones.map((z) => [z, Number(s.zones?.[z] ?? 0)])) })); return <div className="h-72 rounded-xl border bg-white p-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis /><Tooltip /><Bar dataKey="passing" name="Passing %" fill="#6366f1" />{zones.map((z) => <Bar key={z} dataKey={z} stackId="zones" name={zoneLabels[z]} fill={zoneColors[z]} />)}</BarChart></ResponsiveContainer></div>; }
function SubjectCards({ subjects, onZone }: { subjects: AnyRecord[]; onZone: (zone: Zone, courseId: string) => void }) { return <div className="grid gap-4 md:grid-cols-2">{subjects.map((s) => <div key={s.course_id ?? s.course_code} className="rounded-xl border bg-white p-4"><h3 className="font-bold">{s.course_code} — {s.course_title}</h3><p className="text-xs text-slate-500">{s.test_count ?? 0} tests · {s.student_count ?? 0} students</p><div className="mt-3 flex flex-wrap gap-2">{zones.map((z) => <button key={z} onClick={() => onZone(z, String(s.course_id ?? s.course_code))} className="rounded-full px-3 py-1 text-xs font-semibold text-white" style={{ backgroundColor: zoneColors[z] }}>{zoneLabels[z]}: {s.zones?.[z] ?? 0}</button>)}</div></div>)}</div>; }
function SubjectDetail({ detail, close }: { detail: AnyRecord; close: () => void }) { const rows = detail.rows ?? detail.selected_zone_rows ?? [], columns = detail.columns ?? []; const printColumns = ["Student", "Father Name", "Roll No", "Class + Session", "Semester", ...columns.map((c: AnyRecord) => `${c.date ?? c.label} / ${c.total_marks}`), "Percentage"]; const printRows = rows.map((r: AnyRecord) => [r.name, r.father_name ?? "—", r.roll_no ?? "—", `${r.class_name} (${r.session})`, r.semester_number, ...columns.map((c: AnyRecord) => r.cells?.[c.key] ?? "—"), `${Number(r.percentage ?? 0).toFixed(1)}%`]); const print = () => printTable("Subject zone details", printColumns, printRows); return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-6xl overflow-auto rounded-xl bg-white p-5"><div className="mb-3 flex justify-between"><h2 className="font-bold">Subject zone details</h2><div><button onClick={print} className="mr-2 rounded border px-3 py-1"><Printer className="mr-1 inline h-4 w-4" />Print</button><button onClick={close} aria-label="Close"><X /></button></div></div><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="bg-indigo-50"><th className="p-2">Student</th><th className="p-2">Father Name</th><th className="p-2">Roll No</th><th className="p-2">Class + Session</th><th className="p-2">Semester</th>{columns.map((c: AnyRecord) => <th key={c.key} className="p-2">{c.date ?? c.label}<br />/{c.total_marks}</th>)}<th className="p-2">Percentage</th></tr></thead><tbody>{rows.map((r: AnyRecord) => <tr key={r.student_id} className="border-t"><td className="p-2">{r.name}</td><td className="p-2">{r.father_name ?? "—"}</td><td className="p-2">{r.roll_no ?? "—"}</td><td className="p-2">{r.class_name} ({r.session})</td><td className="p-2">{r.semester_number}</td>{columns.map((c: AnyRecord) => <td key={c.key} className="p-2">{r.cells?.[c.key] ?? "—"}</td>)}<td className="p-2">{Number(r.percentage ?? 0).toFixed(1)}%</td></tr>)}</tbody></table></div></div>; }

function ResultScreen({ from, to, setFrom, setTo, studentQ, setStudentQ, students, setStudentId, setStudents, loadReport, report }: any) {
  return <div className="space-y-4"><DateFilters from={from} to={to} setFrom={setFrom} setTo={setTo} /><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={studentQ} onChange={(e) => setStudentQ(e.target.value)} placeholder="Search student name or roll number…" className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm" />{students.length > 0 && <div className="absolute z-10 mt-1 w-full rounded border bg-white shadow">{students.map((s: AnyRecord) => <button key={s.id ?? s.student_id} onClick={() => { setStudentId(s.id ?? s.student_id); setStudentQ(`${s.name} · ${s.roll_no ?? ""}`); setStudents([]); }} className="block w-full px-3 py-2 text-left text-sm hover:bg-indigo-50">{s.name} · {s.roll_no ?? "—"}</button>)}</div>}</div><button onClick={() => void loadReport()} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Load report</button>{report && <ReportTable report={report} />}</div>;
}

function ReportTable({ report }: { report: AnyRecord }) {
  const rows: AnyRecord[] = report.test_rows ?? (report.courses ?? []).flatMap((c: AnyRecord) => (c.tests ?? []).map((t: AnyRecord) => ({ ...t, course_title: t.course_title ?? c.course_title, course_code: t.course_code ?? c.course_code })));
  const student = report.student ?? {}, cls = report.class ?? {}, totals = report.grand_totals ?? {};
  const obtained = (t: AnyRecord) => t.obtained_marks ?? t.obtained ?? 0, total = (t: AnyRecord) => t.total_marks ?? t.total ?? 0;
  const print = () => { const totalsRow = report.grand_totals ?? {}; const photo = student.profile_image_url ? `<img src="${escapePrintHtml(student.profile_image_url)}" style="height:64px;width:64px;border-radius:50%;object-fit:cover" />` : ""; const header = `<div style="display:flex;align-items:center;justify-content:space-between;gap:16px"><img src="/images/logo.png" style="height:64px" /><div style="flex:1"><h2>Result Report</h2><p><b>Student:</b> ${escapePrintHtml(student.name ?? "")} · <b>Roll No:</b> ${escapePrintHtml(student.roll_no ?? "")}</p><p><b>Class:</b> ${escapePrintHtml(cls.name ?? "")} · <b>Session:</b> ${escapePrintHtml(cls.session ?? "")} · <b>Section:</b> ${escapePrintHtml(cls.section ?? "")}</p><p><b>Date:</b> ${escapePrintHtml(report.from_date ?? report.effective_filters?.from_date ?? "")} to ${escapePrintHtml(report.to_date ?? report.effective_filters?.to_date ?? "")} · <b>Report date:</b> ${localDate(new Date())}</p></div>${photo}</div>`; const printRows = rows.map((t) => [t.test_number ?? "—", t.date ?? t.test_date, `${t.course_code ?? ""} ${t.course_title ?? ""}`, t.is_absent ? "Absent (0)" : obtained(t), total(t), `${Number(t.percentage ?? 0).toFixed(1)}%`, t.grade ?? (t.is_absent ? "Absent" : "F")]); printRows.push(["", "Overall", "", totalsRow.obtained ?? totalsRow.obtained_marks ?? 0, totalsRow.total ?? totalsRow.total_marks ?? 0, `${Number(totalsRow.percentage ?? 0).toFixed(1)}%`, totalsRow.grade ?? "F"]); printTable("Result Report", ["Test #", "Date", "Subject", "Obtained Marks", "Total Marks", "Percentage", "Grade"], printRows, header); };
  return <div className="overflow-auto rounded-xl border bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-start gap-4"><img src="/images/logo.png" alt="College logo" className="h-16 w-auto object-contain" /><img src={student.profile_image_url ?? "/images/logo.png"} alt={`${student.name ?? "Student"} profile`} className="h-16 w-16 rounded-full object-cover" /><div><h2 className="text-lg font-bold">Result Report</h2><p>{student.name} · Roll No: {student.roll_no ?? "—"}</p><p className="text-sm text-slate-500">{cls.name ?? "—"} · Session {cls.session ?? "—"} · Section {cls.section ?? "—"} · Semester {report.semester?.number ?? report.semester ?? "—"}</p><p className="text-xs text-slate-500">Date: {report.from_date ?? report.effective_filters?.from_date ?? "—"} to {report.to_date ?? report.effective_filters?.to_date ?? "—"} · Report date: {localDate(new Date())}</p></div></div><button onClick={print} className="rounded border px-3 py-2 text-sm"><FileDown className="mr-1 inline h-4 w-4" />Print / PDF</button></div><table className="mt-4 w-full min-w-[700px] text-left text-xs"><thead><tr className="bg-indigo-50">{["Test #", "Date", "Subject", "Obtained Marks", "Total Marks", "Percentage", "Grade"].map((x) => <th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{rows.map((t, i) => <tr key={`${testKey(t)}-${i}`} className="border-t"><td className="p-2">{t.test_number ?? "—"}</td><td className="p-2">{t.date ?? t.test_date}</td><td className="p-2">{t.course_code ? `${t.course_code} — ` : ""}{t.course_title}</td><td className="p-2">{t.is_absent ? <b className="text-red-600">Absent (0)</b> : obtained(t)}</td><td className="p-2">{total(t)}</td><td className="p-2">{Number(t.percentage ?? 0).toFixed(1)}%</td><td className="p-2 font-semibold">{t.grade ?? (t.is_absent ? "Absent" : "F")}</td></tr>)}<tr className="border-t-2 font-bold"><td colSpan={3} className="p-2">Overall</td><td className="p-2">{totals.obtained ?? totals.obtained_marks ?? 0}</td><td className="p-2">{totals.total ?? totals.total_marks ?? 0}</td><td className="p-2">{Number(totals.percentage ?? 0).toFixed(1)}%</td><td className="p-2">{totals.grade ?? "F"}</td></tr></tbody></table></div>;
}

function ZonesScreen({ from, to, setFrom, setTo, filters, setFilters, optionsData, selected, load, data, loading, detail, setDetail }: any) {
  const fields = [["class_id", "Class"], ["session", "Session"], ["semester_id", "Semester"], ["course_id", "Course"], ["test_series_id", "Test series"]];
  const rows = data?.selected_zone_rows ?? data?.rows ?? data?.zone_rows ?? [];
  const classOption = (optionsData.class_id ?? []).find((x: AnyRecord) => String(x.id) === String(filters.class_id));
  const semesterOption = (optionsData.semester_id ?? []).find((x: AnyRecord) => String(x.id) === String(filters.semester_id));
  const headerText = `CITY COLLEGE (University Campus) · Class ${classOption?.name ?? "All classes"} · Session ${filters.session || classOption?.session || "All"} · Semester ${semesterOption?.name ?? "All"} · Dates/Week ${from} to ${to} · Print Date ${localDate(new Date())}`;
  const print = () => printTable(`${zoneName(selected)} — Overall Zones`, ["Student Roll No", "Name", "Percentage", "Grade", "Zone"], rows.map((r: AnyRecord) => [r.roll_no, r.name, `${Number(r.percentage ?? 0).toFixed(1)}%`, r.grade ?? "F", zoneName(r.zone)]), `<h2>${escapePrintHtml(headerText)}</h2>`);
  return <div className="space-y-4"><DateFilters from={from} to={to} setFrom={setFrom} setTo={setTo} /><div className="flex flex-wrap gap-2 rounded-xl border bg-white p-4">{fields.map(([k, l]) => <Select key={k} label={l} value={filters[k] ?? ""} values={options(optionsData[k] ?? optionsData[k.replace("_id", "s")])} onChange={(v: string) => setFilters({ ...filters, [k]: v })} />)}<button onClick={() => void load()} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm text-white">{loading ? "Loading…" : "Apply filters"}</button></div><div className="rounded-xl border bg-white p-4"><h2 className="font-bold">College Result Zones</h2><p className="text-sm text-slate-500">{headerText}</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{zones.map((z) => <button key={z} onClick={() => void load(z)} className="rounded-xl p-3 text-center font-bold text-white" style={{ backgroundColor: zoneColors[z] }}>{zoneLabels[z]}<div className="text-2xl">{data?.zone_counts?.[z] ?? 0}</div></button>)}</div><div className="flex items-center justify-between"><h2 className="font-bold">{zoneName(selected)} students</h2><button onClick={print} className="rounded border px-3 py-2 text-sm"><Printer className="mr-1 inline h-4 w-4" />Print list</button></div><div className="overflow-auto rounded border bg-white"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="bg-indigo-50"><th className="p-2">Student Roll No</th><th className="p-2">Name</th><th className="p-2">Percentage</th><th className="p-2">Grade</th><th className="p-2">Zone</th><th className="p-2">View Details</th></tr></thead><tbody>{rows.map((r: AnyRecord) => <tr key={r.student_id} className="border-t"><td className="p-2">{r.roll_no}</td><td className="p-2">{r.name}</td><td className="p-2">{Number(r.percentage ?? 0).toFixed(1)}%</td><td className="p-2 font-semibold">{r.grade ?? "F"}</td><td className="p-2">{zoneName(r.zone)}</td><td className="p-2"><button onClick={() => setDetail(r)} className="rounded border px-2 py-1 text-xs">View Details</button></td></tr>)}</tbody></table></div>{detail && <ZoneDetail row={detail} close={() => setDetail(null)} />}</div>;
}

function ZoneDetail({ row, close }: { row: AnyRecord; close: () => void }) {
  const tests = [...(row.tests ?? [])].sort((a: AnyRecord, b: AnyRecord) => String(a.course_title ?? "").localeCompare(String(b.course_title ?? "")));
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-xl bg-white p-5"><div className="flex justify-between"><h2 className="font-bold">{row.name} · Test details</h2><button onClick={close} aria-label="Close"><X /></button></div><table className="mt-4 w-full text-left text-xs"><thead><tr className="bg-indigo-50">{["Date", "Subject", "Series", "Marks", "Total", "Percentage"].map((x) => <th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{tests.map((t: AnyRecord, i) => <tr key={i} className="border-t"><td className="p-2">{t.date}</td><td className="p-2">{t.course_code} {t.course_title}</td><td className="p-2">{t.series_name ?? "—"}</td><td className="p-2">{t.is_absent ? "Absent (0)" : t.obtained_marks ?? 0}</td><td className="p-2">{t.total_marks ?? 0}</td><td className="p-2">{Number(t.percentage ?? 0).toFixed(1)}%</td></tr>)}</tbody></table></div></div>;
}